version: '2'

services:
  # Based on https://realpython.com/blog/python/django-development-with-docker-compose-and-machine/
  # If restart: always is enabled it will run even if the machine is restarted.
  # Docker container ports do not interfere with the host ports

  {{ project_name }}_postgis:
    restart: always
    image: mdillon/postgis:9.5
    volumes:
      - {{ project_name }}_data:/var/lib/postgresql/data
      - ./logs/postgres:/var/log/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"

  {{ project_name }}_redis:
    restart: always
    image: redis:3.0.7

  {{ project_name }}_web:
    restart: always
    build:
      context: .
      dockerfile: ./compose/django/production/Dockerfile
    command: /gunicorn.sh
    volumes:
      - ./media:/code/media
      - ./staticfiles:/code/staticfiles
      - ./{{ project_name }}_management:/code/{{ project_name }}_management
    depends_on:
      - {{ project_name }}_postgis
      - {{ project_name }}_redis
    env_file: .env

  {{ project_name }}_nginx:
    restart: always
    build: ./compose/nginx/production
    depends_on:
      - {{ project_name }}_web
    volumes:
      - ./media:/code/media
      - ./staticfiles:/code/staticfiles
    ports:
      - "80:80"
      - "443:443"

  {{ project_name }}_certbot:
    restart: always
    build: ./compose/certbot/production
    volumes:
      - {{ project_name }}_https_certs:/etc/letsencrypt
      - ./staticfiles:/code/staticfiles
    depends_on:
      - {{ project_name }}_nginx
      - {{ project_name }}_web
    env_file: production.env

volumes:
  {{ project_name }}_data:
  {{ project_name }}_https_certs:
